### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by PhilipSchmid** [mlabouardy/butler#1]
Hi there,

### Description
I just noticed that `butler` fails to import jobs, when Jenkins runs behind a self signed TLS certificate:
```
macbookpro:jenkins phil$ butler jobs import --server jenkins.example.com --username admin --password <my-secret> 
Import job: Git_Sync
Get https://jenkins.example.com:443/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb): x509: certificate signed by unknown authority
```

### Related Issue
None

### Changes proposed 
Would it be possible to add an argument `--skip-tls-check` or something similar do disable the check if the TLS certificate is officially signed?

### Screenshots
None

Thanks

Regards,
Philip

**Comment by digitalfredy** [comment]
Related or same as #10

**Comment by PhilipSchmid** [comment]
Closing this issue since this tool is not needed anymore by my current company and nobody responded within 2 years.

Regards,
Philip
